var familyHead = {
  name: 'Shan',
  wife: 'Anga',
  type:String,
  generation:{
    type:Number,
    val:101
  },
    children : [
    {
      name: 'Chit',
      type:String,
      gender:'Male',
      generation:{
        type:Number,
        val:102
      },
      grandfather:'',
      grandmother:'',
      father:'Shan',
      mother:'Anga',
      wife:'Amba',
      children :[
        {
          name: 'Dritha',
          type:String,
          gender:'Female',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Chit',
          mother:'Amba',
          husband:'Jaya',
          children:[
            {
              name: 'Yodhan',
              type:String,
              gender:'Male',
              generation:{
              type:Number,
              val:104
            },
              grandfather:'Chit',
              grandmother:'Amba',
              father:'Jaya',
              mother:'Dritha',
              husband:'',
            }
          ]
        },
        {
          name: 'Tritha',
          type:String,
          gender:'Female',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Chit',
          mother:'Amba',
          husband:'',
        },
        {
          name: 'Vritha',
          type:String,
          gender:'Male',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Chit',
          mother:'Amba',
          wife:'',
        }
      ]
    },
    {
      name: 'Ish',
      type:String,
      gender:'Male',
      generation:{
        type:Number,
        val:102
      },
      grandfather:'',
      grandmother:'',
      father:'Shan',
      mother:'Anga',
      wife:'',
    },
    {
      name: 'Vich',
      type:String,
      gender:'Male',
      generation:{
        type:Number,
        val:102
      },
      grandfather:'',
      grandmother:'',
      father:'Shan',
      mother:'Anga',
      wife:'Lika',
      children:[
        {
          name: 'Vila',
          type:String,
          gender:'Female',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Vich',
          mother:'Lika',
          husband:'',
      },
      {
        name: 'Chika',
        type:String,
        gender:'Female',
        generation:{
          type:Number,
          val:103
        },
        grandfather:'Shan',
        grandmother:'Anga',
        father:'Vich',
        mother:'Lika',
        husband:'',
    }
    ]
    },
    {
      name: 'Aras',
      type:String,
      gender:'Male',
      generation:{
        type:Number,
        val:102
      },
      grandfather:'',
      grandmother:'',
      father:'Shan',
      mother:'Anga',
      wife:'Chitra',
      children:[
        {
          name: 'Jnki',
          type:String,
          gender:'Female',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Aras',
          mother:'Chitra',
          husband:'Arit',
          children:[
            {
              name: 'Laki',
              type:String,
              gender:'Male',
              generation:{
                type:Number,
                val:104
              },
              grandfather:'Aras',
              grandmother:'Chitra',
              father:'Arit',
              mother:'Jnki',
              wife:'',
            },
            {
              name: 'Lavnya',
              type:String,
              gender:'Female',
              generation:{
                type:Number,
                val:104
              },
              grandfather:'Aras',
              grandmother:'Chitra',
              father:'Arit',
              mother:'Jnki',
              husband:'',
            }
          ]
      },
      {
        name: 'Ahit',
        type:String,
        gender:'Male',
        generation:{
          type:Number,
          val:103
        },
        grandfather:'Shan',
        grandmother:'Anga',
        father:'Aras',
        mother:'Chitra',
        wife:'',
    }
      ]
    },
    {
      name: 'Satya',
      type:String,
      gender:'Female',
      generation:{
        type:Number,
        val:102
      },
      grandfather:'',
      grandmother:'',
      father:'Shan',
      mother:'Anga',
      husband:'Vyan',
      children:[
        {
          name: 'Asva',
          type:String,
          gender:'Male',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Vyan',
          mother:'Satya',
          wife:'Satvy',
          children:[
            {
              name: 'Vasa',
              type:String,
              gender:'Male',
              generation:{
              type:Number,
              val:104
            },
              grandfather:'Vyan',
              grandmother:'Satya',
              father:'Asva',
              mother:'Satvy',
              wife:'',
            }
          ]
        },
        {
          name: 'Vyas',
          type:String,
          gender:'Male',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Vyan',
          mother:'Satya',
          wife:'Krpi',
          children:[
            {
              name: 'Kriya',
              type:String,
              gender:'Male',
              generation:{
                type:Number,
                val:104
              },
              grandfather:'Vyan',
              grandmother:'Satya',
              father:'Vyas',
              mother:'Krpi',
              wife:'',
            },
            {
              name: 'Krithi',
              type:String,
              gender:'Female',
              generation:{
                type:Number,
                val:104
              },
              grandfather:'Vyan',
              grandmother:'Satya',
              father:'Vyas',
              mother:'Krpi',
              husband:'',
            }
          ]
        },
        {
          name: 'Atya',
          type:String,
          gender:'Female',
          generation:{
            type:Number,
            val:103
          },
          grandfather:'Shan',
          grandmother:'Anga',
          father:'Vyan',
          mother:'Satya',
          husband:'',
        }
      ]
    }
  ]
}
module.exports = {
  familyHead
}
